spring:
  application:
    name: app
  config:
    import: optional:classpath:application-dev.yml
  profiles:
    default: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /docs

sentry:
  dsn: https://8b9371ff6e68f74339259f1855db31ec@o4511520372883456.ingest.de.sentry.io/4511520383565904
  send-default-pii: true
