CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    task_index INTEGER,
    description TEXT,
    task_status_id BIGINT NOT NULL,
    assignee_id BIGINT,
    created_at DATE NOT NULL,
    CONSTRAINT fk_tasks_task_status FOREIGN KEY (task_status_id) REFERENCES task_statuses(id),
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES users(id)
);
