CREATE TABLE IF NOT EXISTS labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1000) NOT NULL UNIQUE,
    created_at DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS task_labels (
    task_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, label_id),
    CONSTRAINT fk_task_labels_task FOREIGN KEY (task_id) REFERENCES tasks(id),
    CONSTRAINT fk_task_labels_label FOREIGN KEY (label_id) REFERENCES labels(id)
);
